### ISSUE TITLE
Pass directory input to the publish-npm action

### ISSUE THREAD

**Issue by kirill-ottofeller** [ottofeller/github-actions#2]
add
```yaml
directory:
    description: A directory to run the command in
    default: ./
```
to `inputs:`

and pass it to the https://github.com/ottofeller/github-actions/blob/b8344196aa4560c90fdbe487c921486425dbcef0/publish-npm/action.yml#L38

`directory: ${{ inputs.directory }}`
