### ISSUE TITLE
Error npm-publish auth required

### ISSUE THREAD

**Issue by kirill-ottofeller** [ottofeller/github-actions#4]
Got this error when try to use `npm-publish` action

<img width="771" alt="Screenshot 2022-05-19 at 12 23 45 p m" src="https://user-images.githubusercontent.com/79540316/169260552-c9d0eaae-ce3c-4a4d-8f34-f9c92f81efa0.png">

```yaml
  publish-npm:
    name: Build and Publish npm package
    needs: [set-commit-hash, typecheck, lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: ottofeller/github-actions/publish-npm@main
        with:
          ref: ${{ needs.set-commit-hash.outputs.commit_hash }}
          directory: ./sdk/typescript
          scope: "@ottofeller"
          include-build-step: true
          npm-token: ${{ secrets.NPM_TOKEN }}

```
